name: Create release

on:
  push:
    branches: ["main"]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12.3"
          spec: "main.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "War Thunder Translation Editor"
          options: --onefile, --name "War Thunder Translation Editor", --windowed, --collect-data nicegui, --collect-data webview
